/**
 * Pure transforms for the multi-CLI config compiler — no filesystem access here,
 * so every contract is unit-testable. Orchestration lives in compile.ts.
 * Spec: docs/spec/nxtlvl-multi-cli-compiler.md · Strategy: ADR-028.
 */

export const MANAGED_BEGIN =
  '# --- nxtlvl-managed BEGIN — generated by nxtlvl-core/scripts/multi-cli-compiler; edits inside are overwritten ---';
export const MANAGED_END = '# --- nxtlvl-managed END ---';

/**
 * Claude-only tokens that must never reach another CLI's instruction stream.
 * Matches the sweep pattern used in the ADR-028 portable restructure.
 */
const CLAUDE_ONLY_TOKENS =
  /dangerouslyDisable\w*|claude\.ai\/code|\/interview-me|\/grill-me|\/nxtlvl:|◆/g;

export function findClaudeOnlyTokens(content: string): string[] {
  const matches = content.match(CLAUDE_ONLY_TOKENS) ?? [];
  return [...new Set(matches)];
}

/**
 * Insert or replace the compiler's managed block inside a CLI-owned TOML file.
 * TOML top-level keys must precede any [table] header, so a fresh block goes
 * before the first table. Re-runs replace the block in place — idempotent.
 */
export function upsertManagedTomlBlock(existing: string, bodyLines: string[]): string {
  const block = [MANAGED_BEGIN, ...bodyLines, MANAGED_END];
  const lines = existing.length > 0 ? existing.split('\n') : [];

  const beginIndex = lines.indexOf(MANAGED_BEGIN);
  const endIndex = lines.indexOf(MANAGED_END);
  if (beginIndex !== -1 && endIndex !== -1 && endIndex >= beginIndex) {
    const next = [...lines.slice(0, beginIndex), ...block, ...lines.slice(endIndex + 1)];
    return ensureTrailingNewline(next.join('\n'));
  }

  const firstTableIndex = lines.findIndex((line) => /^\s*\[/.test(line));
  if (firstTableIndex === -1) {
    const pad = lines.length > 0 && lines[lines.length - 1].trim() !== '' ? [''] : [];
    return ensureTrailingNewline([...lines, ...pad, ...block].join('\n'));
  }

  const before = lines.slice(0, firstTableIndex);
  const after = lines.slice(firstTableIndex);
  const pad = before.length > 0 && before[before.length - 1].trim() !== '' ? [''] : [];
  return ensureTrailingNewline([...before, ...pad, ...block, '', ...after].join('\n'));
}

export interface AntigravityRuleOptions {
  trigger: 'always_on' | 'model_decision';
  description: string;
  /** Human-readable source pointer for the generated-file notice. */
  sourceLabel: string;
  body: string;
}

/**
 * Wrap portable markdown as an Antigravity rule: trigger/description frontmatter
 * + a generated-file notice. Currently unused by the global plan — sentinel probes
 * (2026-07-11) showed `~/.gemini/config/agents/` loads nothing (the self-review's
 * global-rules claim was wrong) while `~/.gemini/config/rules/` does load; this
 * emitter targets that rules channel when a real Antigravity supplement materializes.
 */
export function compileAntigravityRule(options: AntigravityRuleOptions): string {
  const header = [
    '---',
    `trigger: ${options.trigger}`,
    `description: ${yamlQuote(options.description)}`,
    '---',
    '',
    `<!-- Generated from ${options.sourceLabel} by nxtlvl-core/scripts/multi-cli-compiler.`,
    '     Do not edit here — edit the source and re-run `npm run compile-multi-cli -- --write`. -->',
    '',
  ].join('\n');
  return ensureTrailingNewline(header + stripFrontmatter(options.body).trimStart());
}

/**
 * Retire-list guard: only files that look like the known hand conversions
 * (Antigravity rule frontmatter) may be deleted — never user-authored content.
 */
export function looksLikeHandConvertedRule(content: string): boolean {
  const head = content.split('\n', 6);
  return head[0]?.trim() === '---' && head.some((line) => /^trigger:\s*\S/.test(line));
}

function stripFrontmatter(content: string): string {
  if (!content.startsWith('---\n')) {
    return content;
  }
  const close = content.indexOf('\n---', 4);
  if (close === -1) {
    return content;
  }
  return content.slice(content.indexOf('\n', close + 1) + 1);
}

function yamlQuote(value: string): string {
  return JSON.stringify(value);
}

function ensureTrailingNewline(content: string): string {
  return content.endsWith('\n') ? content : `${content}\n`;
}
